'use client';

import { useState, useCallback } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Upload, FileText, Image, Mic, CheckCircle, Clock, AlertCircle,
  Network, ChevronDown, ChevronUp, RefreshCw, CloudUpload, ExternalLink, Download,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { toast } from 'sonner';
import Link from 'next/link';
import api from '@/lib/api';
import IngestionPipeline from '@/components/features/IngestionPipeline';
import { useTranslation } from '@/hooks/useTranslation';

const STATUS_CONFIG = {
  pending:    { icon: Clock,       color: 'text-yellow-600 dark:text-yellow-400', bg: 'bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800/40', label: 'Pending' },
  processing: { icon: Clock,       color: 'text-blue-600 dark:text-blue-400',   bg: 'bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800/40',    label: 'Processing' },
  completed:  { icon: CheckCircle, color: 'text-green-600 dark:text-green-400',  bg: 'bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800/40',  label: 'Completed' },
  failed:     { icon: AlertCircle, color: 'text-red-600 dark:text-red-400',      bg: 'bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/40',         label: 'Failed' },
};

const TYPE_ICONS = { image: Image, audio: Mic, document: FileText, text: FileText };

function buildExportText(ingestion, fileName) {
  const lines = [];
  lines.push(`MemoryAI Nigeria — Analysis Report`);
  lines.push(`File: ${fileName || 'Unknown'}`);
  lines.push(`Detected Language: ${ingestion.detectedLanguage || ''}`);
  if (ingestion.outputLanguage && ingestion.outputLanguage !== ingestion.detectedLanguage)
    lines.push(`Output Language: ${ingestion.outputLanguage}`);
  lines.push(`Content Type: ${(ingestion.contentType || '').replace(/_/g, ' ')}`);
  lines.push('');
  if (ingestion.metadata?.title) lines.push(`Title: ${ingestion.metadata.title}`);
  if (ingestion.summaries?.short) { lines.push(''); lines.push('Summary:'); lines.push(ingestion.summaries.short); }
  if (ingestion.summaries?.medium) { lines.push(''); lines.push('Detailed Summary:'); lines.push(ingestion.summaries.medium); }
  if (ingestion.aiUnderstanding?.mainTheme) { lines.push(''); lines.push(`Main Theme: ${ingestion.aiUnderstanding.mainTheme}`); }
  if (ingestion.aiUnderstanding?.moralLessons?.length) {
    lines.push(''); lines.push('Moral Lessons:');
    ingestion.aiUnderstanding.moralLessons.forEach((l) => lines.push(`  • ${l}`));
  }
  if (ingestion.aiUnderstanding?.culturalMeaning) { lines.push(''); lines.push('Cultural Meaning:'); lines.push(ingestion.aiUnderstanding.culturalMeaning); }
  if (ingestion.aiUnderstanding?.historicalContext) { lines.push(''); lines.push('Historical Context:'); lines.push(ingestion.aiUnderstanding.historicalContext); }
  if (ingestion.aiUnderstanding?.educationalValue) { lines.push(''); lines.push('Educational Value:'); lines.push(ingestion.aiUnderstanding.educationalValue); }
  const e = ingestion.entities || {};
  const entityGroups = [
    ['People', e.people], ['Places', e.places], ['Communities', e.communities],
    ['Traditions', e.traditions], ['Festivals', e.festivals], ['Keywords', e.keywords],
  ].filter(([, v]) => v?.length);
  if (entityGroups.length) {
    lines.push(''); lines.push('Extracted Entities:');
    entityGroups.forEach(([label, items]) => lines.push(`  ${label}: ${items.join(', ')}`));
  }
  if (ingestion.metadata?.tags?.length) { lines.push(''); lines.push(`Tags: ${ingestion.metadata.tags.join(', ')}`); }
  lines.push(''); lines.push('— Generated by MemoryAI Nigeria');
  return lines.join('\n');
}

function exportAsTxt(ingestion, fileName) {
  const content = buildExportText(ingestion, fileName);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `${(fileName || 'analysis').replace(/\.[^.]+$/, '')}-memoryai.txt`;
  a.click(); URL.revokeObjectURL(url);
}

function exportAsDoc(ingestion, fileName) {
  const baseName = (fileName || 'analysis').replace(/\.[^.]+$/, '');
  const e = ingestion.entities || {};
  const entityGroups = [
    ['People', e.people], ['Places', e.places], ['Communities', e.communities],
    ['Traditions', e.traditions], ['Festivals', e.festivals], ['Keywords', e.keywords],
  ].filter(([, v]) => v?.length);

  const row = (label, value) => value
    ? `<tr><td style="font-weight:bold;padding:6px 12px 6px 0;vertical-align:top;white-space:nowrap;color:#555;width:160px">${label}</td><td style="padding:6px 0">${value}</td></tr>`
    : '';

  const section = (title, content) =>
    `<h3 style="margin:20px 0 6px;font-size:13px;color:#1a1a1a;border-bottom:1px solid #ddd;padding-bottom:4px">${title}</h3><p style="margin:0;line-height:1.7;font-size:12px">${content}</p>`;

  const html = `
<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
  body{font-family:Arial,sans-serif;font-size:12px;color:#1a1a1a;margin:40px;line-height:1.6}
  h1{font-size:18px;margin-bottom:4px}
  h2{font-size:14px;color:#444;font-weight:normal;margin-top:0}
  table{border-collapse:collapse;width:100%}
  .badge{display:inline-block;background:#f0f0f0;border-radius:4px;padding:2px 8px;margin:2px;font-size:11px}
  .footer{margin-top:40px;font-size:10px;color:#999;border-top:1px solid #eee;padding-top:8px}
</style>
</head><body>
<h1>MemoryAI Nigeria — Analysis Report</h1>
<h2>${baseName}</h2>
<table>
  ${row('Detected Language', ingestion.detectedLanguage)}
  ${ingestion.outputLanguage && ingestion.outputLanguage !== ingestion.detectedLanguage ? row('Output Language', ingestion.outputLanguage) : ''}
  ${row('Content Type', (ingestion.contentType || '').replace(/_/g, ' '))}
  ${row('Title', ingestion.metadata?.title)}
  ${row('Reading Time', ingestion.metadata?.estimatedReadingTime)}
</table>
${ingestion.summaries?.short ? section('Summary', ingestion.summaries.short) : ''}
${ingestion.summaries?.medium ? section('Detailed Summary', ingestion.summaries.medium) : ''}
${ingestion.aiUnderstanding?.mainTheme ? section('Main Theme', ingestion.aiUnderstanding.mainTheme) : ''}
${ingestion.aiUnderstanding?.moralLessons?.length ? section('Moral Lessons', ingestion.aiUnderstanding.moralLessons.map(l => `• ${l}`).join('<br>')) : ''}
${ingestion.aiUnderstanding?.culturalMeaning ? section('Cultural Meaning', ingestion.aiUnderstanding.culturalMeaning) : ''}
${ingestion.aiUnderstanding?.historicalContext ? section('Historical Context', ingestion.aiUnderstanding.historicalContext) : ''}
${ingestion.aiUnderstanding?.educationalValue ? section('Educational Value', ingestion.aiUnderstanding.educationalValue) : ''}
${entityGroups.length ? `<h3 style="margin:20px 0 6px;font-size:13px;color:#1a1a1a;border-bottom:1px solid #ddd;padding-bottom:4px">Extracted Entities</h3><table>${entityGroups.map(([label, items]) => row(label, items.map(i => `<span class="badge">${i}</span>`).join(' '))).join('')}</table>` : ''}
${ingestion.metadata?.tags?.length ? section('Tags', ingestion.metadata.tags.map(t => `<span class="badge">${t}</span>`).join(' ')) : ''}
<div class="footer">— Generated by MemoryAI Nigeria</div>
</body></html>`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `${baseName}-memoryai.doc`;
  a.click(); URL.revokeObjectURL(url);
}

function IngestionResultPanel({ uploadId, fileName }) {
  const { t } = useTranslation();
  const [translateLang, setTranslateLang] = useState('');
  const [translation, setTranslation] = useState(null);
  const [translating, setTranslating] = useState(false);

  const { data, isLoading, isError } = useQuery({
    queryKey: ['ingestion-result', uploadId],
    queryFn: () => api.get(`/ingestion/${uploadId}/result`).then((r) => r.data.data),
    staleTime: 1000 * 60 * 5,
  });

  const translateContent = async (lang) => {
    const text = data?.ingestion?.summaries?.medium || data?.ingestion?.summaries?.short;
    if (!text) return toast.info('No summary to translate yet');
    setTranslateLang(lang);
    setTranslating(true);
    setTranslation(null);
    try {
      const res = await api.post('/education/translate-text', { text, targetLanguage: lang });
      setTranslation(res.data.data?.translation || res.data.data?.translatedText || res.data.data);
    } catch {
      // fallback: try stories translate with content
      try {
        const res2 = await api.post('/education/lesson', {
          content: text,
          language: lang,
          audience: 'adult',
        });
        setTranslation(res2.data.data?.lesson?.introduction || 'Translation not available via this route.');
      } catch {
        toast.error('Translation failed');
      }
    }
    setTranslating(false);
  };

  if (isLoading) return <div className="text-xs text-muted-foreground py-2">Loading results…</div>;
  if (isError || !data?.ingestion) return <div className="text-xs text-destructive py-2">Could not load results.</div>;

  const { ingestion } = data;

  return (
    <div className="space-y-3 pt-3 border-t border-border/50">
      {ingestion.metadata?.title && (
        <p className="text-sm font-semibold">{ingestion.metadata.title}</p>
      )}

      <div className="flex flex-wrap gap-1.5">
        {ingestion.detectedLanguage && (
          <Badge variant="secondary" className="text-xs capitalize">Detected: {ingestion.detectedLanguage}</Badge>
        )}
        {ingestion.outputLanguage && ingestion.outputLanguage !== ingestion.detectedLanguage && (
          <Badge variant="default" className="text-xs capitalize">Output: {ingestion.outputLanguage}</Badge>
        )}
        {ingestion.contentType && (
          <Badge variant="secondary" className="text-xs capitalize">{ingestion.contentType.replace(/_/g, ' ')}</Badge>
        )}
        {ingestion.aiUnderstanding?.mainTheme && (
          <Badge variant="outline" className="text-xs">{ingestion.aiUnderstanding.mainTheme}</Badge>
        )}
        {(ingestion.aiUnderstanding?.subThemes || []).slice(0, 4).map((t) => (
          <Badge key={t} variant="outline" className="text-xs">{t}</Badge>
        ))}
      </div>

      {ingestion.summaries?.short && (
        <div>
          <p className="section-label mb-1">{t('summary')}</p>
          <p className="text-xs leading-relaxed">{ingestion.summaries.short}</p>
        </div>
      )}

      {ingestion.summaries?.medium && (
        <div>
          <p className="section-label mb-1">{t('detailedSummary')}</p>
          <p className="text-xs leading-relaxed">{ingestion.summaries.medium}</p>
        </div>
      )}

      {ingestion.aiUnderstanding?.moralLessons?.length > 0 && (
        <div>
          <p className="section-label mb-1">{t('moralLessons')}</p>
          <ul className="space-y-0.5">
            {ingestion.aiUnderstanding.moralLessons.map((l, i) => (
              <li key={i} className="text-xs">• {l}</li>
            ))}
          </ul>
        </div>
      )}

      {ingestion.aiUnderstanding?.culturalMeaning && (
        <div>
          <p className="section-label mb-1">{t('culturalMeaning')}</p>
          <p className="text-xs leading-relaxed">{ingestion.aiUnderstanding.culturalMeaning}</p>
        </div>
      )}

      {ingestion.aiUnderstanding?.historicalContext && (
        <div>
          <p className="section-label mb-1">{t('historicalContext')}</p>
          <p className="text-xs leading-relaxed">{ingestion.aiUnderstanding.historicalContext}</p>
        </div>
      )}

      {(() => {
        const e = ingestion.entities || {};
        const groups = [
          { label: 'People', items: e.people },
          { label: 'Places', items: e.places },
          { label: 'Communities', items: e.communities },
          { label: 'Traditions', items: e.traditions },
          { label: 'Festivals', items: e.festivals },
          { label: 'Medicinal Plants', items: e.medicinalPlants },
          { label: 'Animals', items: e.animals },
          { label: 'Foods', items: e.foods },
          { label: 'Keywords', items: e.keywords },
        ].filter((g) => g.items?.length);

        if (!groups.length) return null;
        return (
          <div>
            <p className="section-label mb-2">{t('extractedEntities')}</p>
            <div className="space-y-1.5">
              {groups.map(({ label, items }) => (
                <div key={label} className="flex flex-wrap items-start gap-1">
                  <span className="text-xs text-muted-foreground w-24 shrink-0 pt-0.5">{label}:</span>
                  <div className="flex flex-wrap gap-1">
                    {items.slice(0, 6).map((item) => (
                      <Badge key={item} variant="secondary" className="text-xs">{item}</Badge>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        );
      })()}

      {ingestion.metadata?.tags?.length > 0 && (
        <div>
          <p className="section-label mb-1">{t('tags')}</p>
          <div className="flex flex-wrap gap-1">
            {ingestion.metadata.tags.map((tag) => (
              <Badge key={tag} variant="outline" className="text-xs">{tag}</Badge>
            ))}
          </div>
        </div>
      )}

      {ingestion.aiUnderstanding?.educationalValue && (
        <div>
          <p className="section-label mb-1">{t('educationalValue')}</p>
          <p className="text-xs leading-relaxed">{ingestion.aiUnderstanding.educationalValue}</p>
        </div>
      )}

      {/* Translate summary */}
      {(ingestion.summaries?.short || ingestion.summaries?.medium) && (
        <div className="border-t border-border/50 pt-3">
          <p className="section-label mb-2">🌍 Translate Summary</p>
          <div className="flex flex-wrap gap-1.5 mb-2">
            {['hausa', 'yoruba', 'igbo', 'english', 'pidgin'].map((lang) => (
              <button
                key={lang}
                onClick={() => translateContent(lang)}
                disabled={translating}
                className={[
                  'px-2.5 py-1 rounded-full text-xs capitalize border transition-all',
                  translateLang === lang && translation
                    ? 'gradient-brand text-white border-transparent'
                    : 'border-border text-muted-foreground hover:bg-muted',
                ].join(' ')}
              >
                {lang}
              </button>
            ))}
          </div>
          {translating && (
            <p className="text-xs text-muted-foreground animate-pulse flex items-center gap-1">
              <span className="w-3 h-3 rounded-full gradient-brand inline-block animate-pulse" />
              Gemma is translating to {translateLang}…
            </p>
          )}
          {translation && !translating && (
            <div className="bg-primary/5 border border-primary/20 rounded-lg p-3 text-xs leading-relaxed">
              <p className="font-medium text-primary mb-1 capitalize">{translateLang}:</p>
              <p>{typeof translation === 'string' ? translation : JSON.stringify(translation)}</p>
            </div>
          )}
        </div>
      )}
      {/* Export buttons */}
      <div className="border-t border-border/50 pt-3 flex items-center gap-2">
        <span className="text-xs text-muted-foreground">Export:</span>
        <button
          onClick={() => exportAsTxt(ingestion, fileName)}
          className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs border border-border text-muted-foreground hover:bg-muted transition-all"
        >
          <Download className="w-3 h-3" /> TXT
        </button>
        <button
          onClick={() => exportAsDoc(ingestion, fileName)}
          className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs border border-border text-muted-foreground hover:bg-muted transition-all"
        >
          <Download className="w-3 h-3" /> DOC
        </button>
      </div>
    </div>
  );
}

const SAMPLE_UPLOAD_TEXT = `Egungun Festival — Yoruba Ancestor Masquerade

The Egungun festival is one of the most sacred ceremonies in Yoruba religion, celebrated across Yorubaland and in the African diaspora. Egungun are masquerades that represent the spirits of ancestors returning to the world of the living to bless, counsel, and sometimes discipline their descendants.

The masquerades are elaborately costumed figures whose identity must never be revealed — to unmask an Egungun is considered a serious taboo that can bring misfortune. The costumes are made of layers of cloth, often passed down through generations, and the Egungun speaks in a disguised voice.

During the festival, the Egungun moves through the community, blessing households, settling disputes, and reminding the living of their obligations to the ancestors. Certain Egungun are known for healing, others for prophecy, and others for entertainment.

The festival reinforces the Yoruba belief that death is not the end — the ancestors remain active participants in community life, and maintaining good relations with them through ritual and ethical living ensures prosperity and protection for the living.

Elders say: "Iku pa eniyan, ko pa oruko" — death kills a person, but not their name. The Egungun tradition ensures that names and wisdom live on.`;

export default function UploadPage() {
  const { t } = useTranslation();
  const [dragging, setDragging] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [activePipelines, setActivePipelines] = useState({});
  const [expandedResults, setExpandedResults] = useState({});
  const [pipelineLangs, setPipelineLangs] = useState({});
  const [selectedLang, setSelectedLang] = useState('english');
  const queryClient = useQueryClient();

  const uploadSampleText = async () => {
    setUploading(true);
    try {
      const blob = new Blob([SAMPLE_UPLOAD_TEXT], { type: 'text/plain' });
      const file = new File([blob], 'egungun-festival-yoruba.txt', { type: 'text/plain' });
      const formData = new FormData();
      formData.append('file', file);
      const res = await api.post('/uploads', formData);
      const upload = res.data.data?.upload;
      toast.success('Sample text uploaded — AI processing started');
      if (upload?._id) {
        setPipelineLangs((prev) => ({ ...prev, [upload._id]: selectedLang }));
        setActivePipelines((prev) => ({ ...prev, [upload._id]: true }));
      }
      queryClient.invalidateQueries({ queryKey: ['uploads'] });
    } catch (err) {
      toast.error(err.response?.data?.message || 'Upload failed');
    }
    setUploading(false);
  };

  const { data: uploadsData, isLoading } = useQuery({
    queryKey: ['uploads'],
    queryFn: () => api.get('/uploads').then((r) => r.data.data),
    refetchInterval: 8000,
  });

  const handleUpload = useCallback(async (files) => {
    if (!files?.length) return;
    setUploading(true);
    for (const file of Array.from(files)) {
      const formData = new FormData();
      formData.append('file', file);
      try {
        const res = await api.post('/uploads', formData);
        const upload = res.data.data?.upload;
        toast.success(`${file.name} uploaded — AI processing started`);
        if (upload?._id && upload?.extractedText) {
          setPipelineLangs((prev) => ({ ...prev, [upload._id]: selectedLang }));
          setActivePipelines((prev) => ({ ...prev, [upload._id]: true }));
        }
      } catch (err) {
        toast.error(`Failed to upload ${file.name}: ${err.response?.data?.message || err.message}`);
      }
    }
    setUploading(false);
    queryClient.invalidateQueries({ queryKey: ['uploads'] });
  }, [queryClient, selectedLang]);

  const onDrop = useCallback((e) => {
    e.preventDefault();
    setDragging(false);
    handleUpload(e.dataTransfer.files);
  }, [handleUpload]);

  const toggleResult = (id) => setExpandedResults((prev) => ({ ...prev, [id]: !prev[id] }));
  const reAnalyze = (id) => {
    setExpandedResults((prev) => ({ ...prev, [id]: false }));
    setActivePipelines((prev) => ({ ...prev, [id]: true }));
  };

  return (
    <div className="page-container space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="font-serif text-2xl sm:text-3xl font-bold">{t('uploadTitle')}</h1>
          <p className="text-muted-foreground text-sm mt-0.5">{t('uploadDesc2')}</p>
        </div>
        <Link href="/graph">
          <Button variant="outline" size="sm" className="gap-2 shrink-0">
            <Network className="w-4 h-4" />
            <span className="hidden sm:inline">{t('knowledgeGraph')}</span>
            <span className="sm:hidden">{t('graph')}</span>
          </Button>
        </Link>
      </div>

      {/* Drop Zone */}
      <div
        onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
        onDragLeave={() => setDragging(false)}
        onDrop={onDrop}
        className={[
          'border-2 border-dashed rounded-2xl p-8 sm:p-12 text-center transition-all duration-200 cursor-pointer',
          dragging
            ? 'border-primary bg-primary/8 scale-[1.01]'
            : 'border-border/50 hover:border-primary/50 hover:bg-muted/20',
        ].join(' ')}
        onClick={() => document.getElementById('file-input').click()}
        role="button"
        tabIndex={0}
        aria-label="Upload files"
        onKeyDown={(e) => e.key === 'Enter' && document.getElementById('file-input').click()}
      >
        <div className="w-12 h-12 sm:w-14 sm:h-14 rounded-2xl gradient-brand flex items-center justify-center mx-auto mb-4">
          <CloudUpload className="w-6 h-6 sm:w-7 sm:h-7 text-white" />
        </div>
        <h3 className="font-semibold text-base sm:text-lg mb-1.5">
          {dragging ? t('dropNow') : t('dropFiles')}
        </h3>
        <p className="text-muted-foreground text-xs sm:text-sm mb-4">
          Images (JPG, PNG) · Audio (MP3, WAV) · Documents (PDF, DOCX, TXT)
        </p>
        <input
          id="file-input"
          type="file"
          multiple
          className="hidden"
          accept="image/*,audio/*,.pdf,.docx,.txt,.md"
          onChange={(e) => handleUpload(e.target.files)}
        />
        <span className={[
          'inline-flex items-center gap-2 rounded-lg border border-border bg-background px-4 h-9 text-sm font-medium transition-colors hover:bg-muted',
          uploading ? 'opacity-50 pointer-events-none' : '',
        ].join(' ')}>
          <Upload className="w-4 h-4" />
          {uploading ? t('uploading') : t('chooseFiles')}
        </span>
      </div>

      {/* Sample text shortcut */}
      <div className="flex items-center gap-2">
        <span className="text-xs text-muted-foreground">No file? Try a sample:</span>
        <button
          type="button"
          onClick={uploadSampleText}
          disabled={uploading}
          className="filter-chip text-xs"
        >
          🌿 Egungun Festival (Yoruba text)
        </button>
      </div>

      {/* Upload type info */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { icon: Image,    title: 'Images',    desc: 'Handwritten notes, manuscripts — OCR extracts text', color: 'text-blue-500', bg: 'bg-blue-50 dark:bg-blue-900/20' },
          { icon: Mic,      title: 'Audio',     desc: 'Voice recordings, oral histories, storytelling',      color: 'text-purple-500', bg: 'bg-purple-50 dark:bg-purple-900/20' },
          { icon: FileText, title: 'Documents', desc: 'PDF, Word, text files, and markdown',                 color: 'text-green-500', bg: 'bg-green-50 dark:bg-green-900/20' },
        ].map((item) => (
          <Card key={item.title} className="border-border/50">
            <CardContent className="p-3 sm:p-4">
              <div className={`w-8 h-8 rounded-lg ${item.bg} flex items-center justify-center mb-2`}>
                <item.icon className={`w-4 h-4 ${item.color}`} />
              </div>
              <div className="font-medium text-xs sm:text-sm mb-0.5">{item.title}</div>
              <div className="text-xs text-muted-foreground leading-relaxed hidden sm:block">{item.desc}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Uploads list */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h2 className="font-semibold text-base sm:text-lg">{t('yourUploads')}</h2>
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted-foreground">AI output in:</span>
            {['english', 'hausa', 'yoruba', 'igbo', 'pidgin'].map((lang) => (
              <button
                key={lang}
                onClick={() => setSelectedLang(lang)}
                className={[
                  'px-2.5 py-1 rounded-full text-xs capitalize border transition-all',
                  selectedLang === lang
                    ? 'gradient-brand text-white border-transparent'
                    : 'border-border text-muted-foreground hover:bg-muted',
                ].join(' ')}
              >
                {lang}
              </button>
            ))}
          </div>
        </div>
        <div className="space-y-3">
          {isLoading
            ? Array(3).fill(0).map((_, i) => <Skeleton key={i} className="h-20 rounded-xl" />)
            : uploadsData?.map((upload) => {
                const cfg = STATUS_CONFIG[upload.analysisStatus] || STATUS_CONFIG.pending;
                const StatusIcon = cfg.icon;
                const TypeIcon = TYPE_ICONS[upload.uploadType] || FileText;
                const isPipelineActive = activePipelines[upload._id];
                const isResultOpen = expandedResults[upload._id];
                const hasResult = upload.analysisStatus === 'completed' && upload.ingestion?.completedAt;
                const fileUrl = upload.fileUrl && !upload.fileUrl.startsWith('local://') ? upload.fileUrl : null;

                return (
                  <Card key={upload._id} className="border-border/50">
                    <CardContent className="p-4 space-y-3">
                      <div className="flex items-start gap-3">
                        <div className="w-9 h-9 rounded-lg bg-muted flex items-center justify-center shrink-0 mt-0.5">
                          <TypeIcon className="w-4 h-4 text-muted-foreground" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-start justify-between gap-2 mb-1">
                            {fileUrl ? (
                              <a
                                href={fileUrl}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="font-medium text-sm truncate leading-snug hover:text-primary flex items-center gap-1 min-w-0"
                                onClick={(e) => e.stopPropagation()}
                              >
                                <span className="truncate">{upload.originalName}</span>
                                <ExternalLink className="w-3 h-3 shrink-0 text-primary" />
                              </a>
                            ) : (
                              <span className="font-medium text-sm truncate leading-snug">{upload.originalName}</span>
                            )}
                            <Badge variant="secondary" className="text-xs shrink-0 h-5">{upload.uploadType}</Badge>
                          </div>
                          {upload.ingestion?.metadata?.title && !isPipelineActive && (
                            <p className="text-xs font-medium text-foreground">{upload.ingestion.metadata.title}</p>
                          )}
                          {upload.ingestion?.summaries?.short && !isPipelineActive && !isResultOpen && (
                            <p className="text-xs text-muted-foreground line-clamp-2 mt-0.5">
                              {upload.ingestion.summaries.short}
                            </p>
                          )}
                          {upload.ingestion?.aiUnderstanding?.subThemes?.length > 0 && !isPipelineActive && !isResultOpen && (
                            <div className="flex flex-wrap gap-1 mt-1.5">
                              {upload.ingestion.aiUnderstanding.subThemes.slice(0, 3).map((t) => (
                                <Badge key={t} variant="outline" className="text-xs h-4">{t}</Badge>
                              ))}
                            </div>
                          )}
                          {upload.extractedText && !upload.ingestion?.metadata?.title && !isPipelineActive && (
                            <p className="text-xs text-muted-foreground line-clamp-1 mt-0.5">{upload.extractedText}</p>
                          )}
                        </div>
                      </div>

                      {/* Status + actions row */}
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className={`inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full ${cfg.bg} ${cfg.color}`}>
                          <StatusIcon className="w-3 h-3" />
                          {cfg.label}
                        </span>

                        {hasResult && !isPipelineActive && (
                          <Button size="sm" variant="outline" className="gap-1 text-xs h-7 ml-auto" onClick={() => toggleResult(upload._id)}>
                            {isResultOpen ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                            {isResultOpen ? t('hide') : t('viewResults')}
                          </Button>
                        )}

                        {fileUrl && (
                          <a
                            href={fileUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            onClick={(e) => e.stopPropagation()}
                          >
                            <Button size="sm" variant="outline" className="gap-1 text-xs h-7">
                              <ExternalLink className="w-3 h-3" /> View
                            </Button>
                          </a>
                        )}

                        {hasResult && !isPipelineActive && (
                          <Button
                            size="sm" variant="ghost"
                            className="gap-1 text-xs h-7 text-muted-foreground"
                            onClick={() => {
                              setPipelineLangs((prev) => ({ ...prev, [upload._id]: selectedLang }));
                              reAnalyze(upload._id);
                            }}
                            title="Re-run AI analysis"
                          >
                            <RefreshCw className="w-3 h-3" />
                          </Button>
                        )}

                        {(upload.analysisStatus === 'pending' || upload.analysisStatus === 'failed') &&
                          upload.extractedText && !isPipelineActive && (
                          <Button
                            size="sm" variant="outline"
                            className="gap-1 text-xs h-7"
                            onClick={() => {
                              setPipelineLangs((prev) => ({ ...prev, [upload._id]: selectedLang }));
                              setActivePipelines((prev) => ({ ...prev, [upload._id]: true }));
                            }}
                          >
                            {t('runAI')}
                          </Button>
                        )}
                      </div>

                      {/* Stored result panel */}
                      <AnimatePresence>
                        {isResultOpen && !isPipelineActive && (
                          <motion.div
                            key="result"
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: 'auto' }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                          >
                            <IngestionResultPanel uploadId={upload._id} fileName={upload.originalName} />
                          </motion.div>
                        )}
                      </AnimatePresence>

                      {/* Live pipeline */}
                      {isPipelineActive && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: 'auto' }}
                          className="border-t border-border/50 pt-3"
                        >
                          <IngestionPipeline
                            uploadId={upload._id}
                            outputLanguage={pipelineLangs[upload._id] || selectedLang}
                            onComplete={() => {
                              setActivePipelines((prev) => ({ ...prev, [upload._id]: false }));
                              queryClient.invalidateQueries({ queryKey: ['uploads'] });
                              queryClient.invalidateQueries({ queryKey: ['ingestion-result', upload._id] });
                              queryClient.invalidateQueries({ queryKey: ['graph'] });
                              queryClient.invalidateQueries({ queryKey: ['graph-stats'] });
                              setExpandedResults((prev) => ({ ...prev, [upload._id]: true }));
                            }}
                            onError={(msg) => {
                              setActivePipelines((prev) => ({ ...prev, [upload._id]: false }));
                              toast.error(msg || 'AI processing failed');
                            }}
                          />
                        </motion.div>
                      )}
                    </CardContent>
                  </Card>
                );
              })
          }
        </div>
      </div>
    </div>
  );
}
